[build]
builder = "nixpacks"
buildCommand = "../../mvnw clean package -DskipTests -pl services/otp-service -am"

[deploy]
startCommand = "java -jar -Dspring.profiles.active=railway target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "8090"
SPRING_PROFILES_ACTIVE = "railway"