CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

SET timezone = 'UTC';

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
        CREATE USER '${POSTGRES_USER}' WITH PASSWORD '${POSTGRES_PASSWORD}';
    END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE '${POSTGRES_DB}' TO '${POSTGRES_USER}';

ALTER DATABASE '${POSTGRES_DB}' SET search_path TO public, auth;